name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v2

      # Gera a animação da cobrinha
      - uses: Platane/snk@v2
        with:
          github_user_name: savioquixaba
          outputs: dist/snake.svg

      # Publica o arquivo no branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
