name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: savioquixaba # Seu nome de usuário no GitHub
          outputs: dist/snake.svg

      - name: Push generated Snake Game to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
